---

- hosts: all
  become: true
  gather_facts: yes
  tasks:

  - name: install htop package
    tags: install
    package:
      name: "{{ htop_package }}"
      state: latest
      update_cache: yes
    when: ansible_facts["distribution"] == "Fedora"

  - name: copy file
    tags: copy
    copy: 
      src: testfile
      dest: /home/abhi/testfile
      owner: abhi
      group: abhi
      mode: 0644

  - name: edit file
    tags: edit file
    lineinfile:
      path: /home/abhi/testfile
      regexp: '^hello'
      line: I am edited by ansible
