---

- hosts: all
  become: true
  gather_facts: yes
  tasks:

  - name: install htop package
    tags: install
    package:
      name: "{{ htop_package }}"
      state: latest
      update_cache: yes
    when: ansible_facts["distribution"] == "Fedora"

  - name: copy file
    tags: copy
    copy: 
      src: testfile
      dest: /home/abhi/testfile
      owner: abhi
      group: abhi
      mode: 0644
